[log]
# Could be the folowing:
# NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
level='INFO'

[sensor]
serial_port='/dev/ttyACM0'
baud_rate_bps=9600
serial_timeout_seconds=5

[database]
name='tempidity_readings.db'
